apiVersion: v1
appVersion: 2.14.1.0-b36
description: YugaWare is YugaByte Database's Orchestration and Management console.
home: https://www.yugabyte.com
icon: https://avatars0.githubusercontent.com/u/17074854?s=200&v=4
maintainers:
- email: ram@yugabyte.com
  name: Ram Sri
- email: arnav@yugabyte.com
  name: Arnav Agarwal
name: yugaware
version: 2.14.1
